Script started on Mon 21 Jan 2019 08:34:19 AM EST
]0;agh0030@agh0030:~/comp3500[?1034h[agh0030@agh0030 comp3500]$ gcc -v
Using built-in specs.
Target: i686-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch=i686 --build=i686-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC) 
]0;agh0030@agh0030:~/comp3500[agh0030@agh0030 comp3500]$ gcc -g -lm - [Ko -[Ksimple simple.c
]0;agh0030@agh0030:~/comp3500[agh0030@agh0030 comp3500]$ man ldd
[?1049h[?1h=LDD(1)                     Linux Programmer’s Manual                    LDD(1)

[1mNAME[0m
       ldd - print shared library dependencies

[1mSYNOPSIS[0m
       [1mldd[0m [OPTION]... FILE...

[1mDESCRIPTION[0m
       [1mldd[0m  prints  the  shared  libraries  required by each program or shared
       library specified on the command line.

[1mOPTIONS[0m
       [1m--version[0m
              Print the version number of [1mldd[0m.

       [1m-v[0m [1m--verbose[0m
              Print all information, including, for example, symbol versioning
              information.

       [1m-u[0m [1m--unused[0m
              Print unused direct dependencies.  (Since glibc 2.3.4.)

:[K[K[?1l>[?1049l]0;agh0030@agh0030:~/comp3500[agh0030@agh0030 comp3500]$ ldd siom[K[Kmple
	linux-gate.so.1 =>  (0x00e6c000)
	libm.so.6 => /lib/libm.so.6 (0x00d98000)
	libc.so.6 => /lib/libc.so.6 (0x00419000)
	/lib/ld-linux.so.2 (0x800e9000)
]0;agh0030@agh0030:~/comp3500[agh0030@agh0030 comp3500]$ ./simple
1
]0;agh0030@agh0030:~/comp3500[agh0030@agh0030 comp3500]$ gdb
[?1034hGNU gdb (GDB) Red Hat Enterprise Linux (7.2-92.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Breakpoint 1 at 0x804844d: file simple.c, line 5.
Breakpoint 2 at 0x8048364
.gdbinit:4: Error in sourced command file:
The program has no registers now.
(gdb) r
Starting program: /home/agh0030/comp3500/simple 

Breakpoint 1, main () at simple.c:5
5	  int arr[] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.212.el6.i686
(gdb) n
7	  int avg = 0;
(gdb) s
10	  for (i = 0; i < 10; i++)
(gdb) c
Continuing.
1

Program exited normally.
(gdb) exit
Undefined command: "exit".  Try "help".
(gdb) quit
]0;agh0030@agh0030:~/comp3500[agh0030@agh0030 comp3500]$ exit
exit

Script done on Mon 21 Jan 2019 08:35:29 AM EST
