Script started on Mon 21 Jan 2019 05:59:39 AM EST
]0;agh0030@agh0030:~[?1034h[agh0030@agh0030 ~]$ man pwd
[?1049h[?1h=PWD(1)                           User Commands                          PWD(1)

[1mNAME[0m
       pwd - print name of current/working directory

[1mSYNOPSIS[0m
       [1mpwd[0m [[4mOPTION[24m]...

[1mDESCRIPTION[0m
       Print the full filename of the current working directory.

       [1m-L[0m, [1m--logical[0m
              use PWD from environment, even if it contains symlinks

       [1m-P[0m, [1m--physical[0m
              avoid all symlinks

       [1m--help[0m display this help and exit

       [1m--version[0m
              output version information and exit

       NOTE:  your shell may have its own version of pwd, which usually super-
:[K[K[?1l>[?1049l]0;agh0030@agh0030:~[agh0030@agh0030 ~]$ ced [K[Kd[K[Kd /home/agh0030/de[K[KDesktop/
]0;agh0030@agh0030:~/Desktop[agh0030@agh0030 Desktop]$ pwd
/home/agh0030/Desktop
]0;agh0030@agh0030:~/Desktop[agh0030@agh0030 Desktop]$ ls
dhclient.txt  dhclient.txt~  example.txt
]0;agh0030@agh0030:~/Desktop[agh0030@agh0030 Desktop]$ lsmk[K[K[K[Kmkdir F[Kfolder
]0;agh0030@agh0030:~/Desktop[agh0030@agh0030 Desktop]$ cp example[K[K[K[Kp[Kmple.[K /home/agh0030/
cp: cannot stat `example': No such file or directory
]0;agh0030@agh0030:~/Desktop[agh0030@agh0030 Desktop]$ cp example.txt /home/agh0030/
]0;agh0030@agh0030:~/Desktop[agh0030@agh0030 Desktop]$ mv example.txt /home/agh0300[K[K[K030/d[KDesktop/folder
]0;agh0030@agh0030:~/Desktop[agh0030@agh0030 Desktop]$ rm dhclient.txt
]0;agh0030@agh0030:~/Desktop[agh0030@agh0030 Desktop]$ mkdir example2[K[K[K[K[K[K[K[K[K[K[K[K[K[Kmkdir folder2
]0;agh0030@agh0030:~/Desktop[agh0030@agh0030 Desktop]$ rmdir folder2
]0;agh0030@agh0030:~/Desktop[agh0030@agh0030 Desktop]$ chmod 776 example
]0;agh0030@agh0030:~/Desktop[agh0030@agh0030 Desktop]$ clear
[H[2J]0;agh0030@agh0030:~/Desktop[agh0030@agh0030 Desktop]$ top
[H[2J(B[mtop - 06:08:15 up 25 min,  4 users,  load average: 0.00, 0.00, 0.00(B[m[39;49m[K
Tasks:(B[m[39;49m(B[m 126 (B[m[39;49mtotal,(B[m[39;49m(B[m   1 (B[m[39;49mrunning,(B[m[39;49m(B[m 125 (B[m[39;49msleeping,(B[m[39;49m(B[m   0 (B[m[39;49mstopped,(B[m[39;49m(B[m   0 (B[m[39;49mzombie(B[m[39;49m[K
Cpu(s):(B[m[39;49m(B[m  1.6%(B[m[39;49mus,(B[m[39;49m(B[m  0.8%(B[m[39;49msy,(B[m[39;49m(B[m  0.0%(B[m[39;49mni,(B[m[39;49m(B[m 97.0%(B[m[39;49mid,(B[m[39;49m(B[m  0.5%(B[m[39;49mwa,(B[m[39;49m(B[m  0.0%(B[m[39;49mhi,(B[m[39;49m(B[m  0.1%(B[m[39;49msi,(B[m[39;49m(B[m  0.0%(B[m[39;49mst(B[m[39;49m[K
Mem: (B[m[39;49m(B[m   248564k (B[m[39;49mtotal,(B[m[39;49m(B[m   244464k (B[m[39;49mused,(B[m[39;49m(B[m     4100k (B[m[39;49mfree,(B[m[39;49m(B[m    11052k (B[m[39;49mbuffers(B[m[39;49m[K
Swap:(B[m[39;49m(B[m  1121276k (B[m[39;49mtotal,(B[m[39;49m(B[m    36956k (B[m[39;49mused,(B[m[39;49m(B[m  1084320k (B[m[39;49mfree,(B[m[39;49m(B[m    89072k (B[m[39;49mcached(B[m[39;49m[K
[6;1H
[7m  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND            (B[m[39;49m[K
(B[m    1 root      20   0  2900  680  520 S  0.0  0.3   0:00.96 init               (B[m[39;49m
(B[m    2 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kthreadd           (B[m[39;49m
(B[m    3 root      RT   0     0    0    0 S  0.0  0.0   0:00.00 migration/0        (B[m[39;49m
(B[m    4 root      20   0     0    0    0 S  0.0  0.0   0:00.00 ksoftirqd/0        (B[m[39;49m
(B[m    5 root      RT   0     0    0    0 S  0.0  0.0   0:00.00 stopper/0          (B[m[39;49m
(B[m    6 root      RT   0     0    0    0 S  0.0  0.0   0:00.00 watchdog/0         (B[m[39;49m
(B[m    7 root      20   0     0    0    0 S  0.0  0.0   0:00.11 events/0           (B[m[39;49m
(B[m    8 root      20   0     0    0    0 S  0.0  0.0   0:00.00 events/0           (B[m[39;49m
(B[m    9 root      20   0     0    0    0 S  0.0  0.0   0:00.00 events_long/0      (B[m[39;49m
(B[m   10 root      20   0     0    0    0 S  0.0  0.0   0:00.00 events_power_ef    (B[m[39;49m
(B[m   11 root      20   0     0    0    0 S  0.0  0.0   0:00.00 cgroup             (B[m[39;49m
(B[m   12 root      20   0     0    0    0 S  0.0  0.0   0:00.00 khelper            (B[m[39;49m
(B[m   13 root      20   0     0    0    0 S  0.0  0.0   0:00.00 netns              (B[m[39;49m
(B[m   14 root      20   0     0    0    0 S  0.0  0.0   0:00.00 async/mgr          (B[m[39;49m
(B[m   15 root      20   0     0    0    0 S  0.0  0.0   0:00.00 pm                 (B[m[39;49m
(B[m   16 root      20   0     0    0    0 S  0.0  0.0   0:00.00 sync_supers        (B[m[39;49m
(B[m   17 root      20   0     0    0    0 S  0.0  0.0   0:00.00 bdi-default        (B[m[39;49m[6;1H[K[25;1H[?12l[?25h
]0;agh0030@agh0030:~/Desktop[agh0030@agh0030 Desktop]$ who
agh0030  tty1         2019-01-21 05:42 (:0)
agh0030  pts/0        2019-01-21 05:43 (:0.0)
agh0030  pts/1        2019-01-21 05:51 (:0.0)
agh0030  pts/2        2019-01-21 05:59
]0;agh0030@agh0030:~/Desktop[agh0030@agh0030 Desktop]$ nproc
1
]0;agh0030@agh0030:~/Desktop[agh0030@agh0030 Desktop]$ exit[K[K[K[Kexit
exit

Script done on Mon 21 Jan 2019 06:08:36 AM EST
